services:
  # Central SSO API
  central-sso:
    build:
      context: ./apps/central-sso
      dockerfile: Dockerfile
    container_name: ${CENTRAL_SSO_CONTAINER:-central-sso}
    ports:
      - "${CENTRAL_SSO_PORT:-8000}:8000"
    volumes:
      - central_sso_app_data:/var/www/html
      - /var/www/html/vendor
    env_file:
      - .env.shared
      - .env.central-sso
    depends_on:
      - mariadb
    networks:
      - sso-network
      - cloudflare-net

  # Tenant 1 Application
  tenant1-app:
    build:
      context: ./apps/tenant1-app
      dockerfile: Dockerfile
    container_name: ${TENANT1_CONTAINER:-tenant1-app}
    ports:
      - "${TENANT1_PORT:-8001}:8000"
    volumes:
      - tenant1_app_data:/var/www/html
      - /var/www/html/vendor
    env_file:
      - .env.shared
      - .env.tenant1-app
    depends_on:
      - mariadb
      - central-sso
    networks:
      - sso-network
      - cloudflare-net

  # Tenant 2 Application
  tenant2-app:
    build:
      context: ./apps/tenant2-app
      dockerfile: Dockerfile
    container_name: ${TENANT2_CONTAINER:-tenant2-app}
    ports:
      - "${TENANT2_PORT:-8002}:8000"
    volumes:
      - tenant2_app_data:/var/www/html
      - /var/www/html/vendor
    env_file:
      - .env.shared
      - .env.tenant2-app
    depends_on:
      - mariadb
      - central-sso
    networks:
      - sso-network
      - cloudflare-net

  # MariaDB Database
  mariadb:
    image: mariadb:${MARIADB_VERSION:-10.9}
    container_name: ${MARIADB_CONTAINER:-sso-mariadb}
    ports:
      - "${MARIADB_EXTERNAL_PORT:-3307}:3306"
    env_file:
      - .env.mariadb
    volumes:
      - ${MARIADB_DATA_VOLUME:-mariadb_data}:/var/lib/mysql
      - ./deploy/database/mariadb/init:/docker-entrypoint-initdb.d
    networks:
      - sso-network

networks:
  sso-network:
    driver: bridge
  cloudflare-net:
    external: true

volumes:
  mariadb_data:
    driver: local
  central_sso_app_data:
    driver: local
  tenant1_app_data:
    driver: local
  tenant2_app_data:
    driver: local
