version: '3.8'

services:
  # Central SSO API
  central-sso:
    build:
      context: ./central-sso
      dockerfile: Dockerfile
    container_name: central-sso
    ports:
      - "8000:8000"
    volumes:
      - ./central-sso:/var/www/html
      - /var/www/html/vendor
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=sso_main
      - DB_USERNAME=sso_user
      - DB_PASSWORD=sso_password
    depends_on:
      - mariadb
    networks:
      - sso-network

  # Tenant 1 Application
  tenant1-app:
    build:
      context: ./tenant1-app
      dockerfile: Dockerfile
    container_name: tenant1-app
    ports:
      - "8001:8000"
    volumes:
      - ./tenant1-app:/var/www/html
      - /var/www/html/vendor
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=tenant1_db
      - DB_USERNAME=sso_user
      - DB_PASSWORD=sso_password
      - CENTRAL_SSO_URL=http://localhost:8000
      - CENTRAL_SSO_API=http://central-sso:8000/api
      - TENANT_SLUG=tenant1
    depends_on:
      - mariadb
      - central-sso
    networks:
      - sso-network

  # Tenant 2 Application
  tenant2-app:
    build:
      context: ./tenant2-app
      dockerfile: Dockerfile
    container_name: tenant2-app
    ports:
      - "8002:8000"
    volumes:
      - ./tenant2-app:/var/www/html
      - /var/www/html/vendor
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=tenant2_db
      - DB_USERNAME=sso_user
      - DB_PASSWORD=sso_password
      - CENTRAL_SSO_URL=http://localhost:8000
      - CENTRAL_SSO_API=http://central-sso:8000/api
      - TENANT_SLUG=tenant2
    depends_on:
      - mariadb
      - central-sso
    networks:
      - sso-network

  # MariaDB Database
  mariadb:
    image: mariadb:10.9
    container_name: sso-mariadb
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=sso_main
      - MYSQL_USER=sso_user
      - MYSQL_PASSWORD=sso_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./infrastructure/database/mariadb/init:/docker-entrypoint-initdb.d
    networks:
      - sso-network

networks:
  sso-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local